### ISSUE TITLE
Red arrow for load order issues displaying incorrectly

### ISSUE THREAD

**Issue by eScribMac** [fluffy-mods/ModManager#99] opened 2020-06-07 22:47 UTC
**Describe the bug**  
Under certain circumstances, the arrow shows up for every single mod that has load order requirements, even though the order is correct.

**Steps to reproduce**  

1. Rimworld with Royalty installed on Steam on Windows 10 64 bit. ModManager and all other mods installed via Workshop. 
2. Open mod menu
3. Select new game
4. Select back and open mod menu again. Arrows now show up. 

**Other mods**  
Many other mods including Hugslib and Harmony, loaded in correct order

**Comment by FluffierThanThou** [comment] 2020-08-11 19:51
duplicate of fluffy-mods/ModManager#112

**Closed as completed by FluffierThanThou** 2020-08-11 19:51 UTC
Labels: bug, unverified
