### ISSUE TITLE
Mods Can't Detect Load Order, Breaks All Mods

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [fluffy-mods/ModManager#96] opened 2020-05-04 19:29 UTC
**The Issue&&
When I open the mod manager, every mod that has any sort of dependency has a red error sign, each one says things like "Must be loaded before/after X", even when they already are in the proper order. This just happened randomly one day, I hadn't changed anything.

**Expected behavior**  
Mods to work normally as they had been.

**Steps to reproduce**  
1. Open game
2. Open mod manager
3. Close mod manager
4. Open mod manager
5. Everything broken

**Other mods**  
Doesn't matter if it's a full mod list or just MM and Harmony, it all breaks

**Output log**  
https://gist.github.com/741a5ffdb03041424cf66cd2371ab468

**Screenshots**  
https://www.reddit.com/r/RimWorld/comments/g7cscd/mod_list_broken/ A reddit post I made when the issue first happened, screenshots and logs are included

**Environment**  
Windows 10 64bit
 
**Game**
 64 bits
 Steam
Latest

**Comment by FluffierThanThou** [comment] 2020-08-11 19:53
duplicate of fluffy-mods/ModManager#112

**Closed as completed by FluffierThanThou** 2020-08-11 19:53 UTC
Labels: bug, unverified
